version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: yarn test --passWithNoTests

  deploy-dev:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: 's3://aw-test-cube'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  build-and-push:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop